const actionType ={
    ADD_APOIO:'ADD_APOIO',
    REMOVER_APOIO:'REMOVER_APOIO',
    MODIFICAR_COMPRIMENTO:'MODIFICAR_COMPRIMENTO',
    SALVAR:'SALVAR',
    ADD_MOMENTO:'ADD_MOMENTO',
    REMOVER_MOMENTO:'REMOVER_MOMENTO',
    ADD_ARMADURA:'ADD_ARMADURA',
    REMOVER_ARMADURA:'REMOVER_ARMADURA',
    ADD_CARACTERISTICAS:'ADD_CARACTERISTICAS',
    ADD_SECAO:'ADD_SECAO',
    REMOVER_SECAO:'REMOVER_SECAO',
    CADASTRAR:'CADASTRAR'
}

export default actionType